version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./bedrock/:/var/www/html/bedrock/
      - ./nginx/:/etc/nginx/
    depends_on:
      - php
    networks:
      - app-network
    restart: always

  php:
    build: .
    volumes:
      - ./bedrock/:/var/www/html/bedrock/
      - ./php-etc/:/usr/local/etc/
    networks:
      - app-network
    restart: always
    working_dir: /var/www/html/bedrock
    command: sh -c "
        composer install
        php-fpm
      "

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme # Change db root password
      MYSQL_DATABASE: changeme # Change db name
      MYSQL_USER: changeme # Change db user
      MYSQL_PASSWORD: changeme # Change db user password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
